ozone_v4/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('', include('staff.urls')),
]

urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('', include('observations.urls')),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ozone_v4/staff/urls.py
from django.urls import path
# from django.conf.urls import url

# from rest_framework import routers

from .views import WorkersListView
from .views import WorkersAPIList
from .views import WorkersDetailView
from .views import WorkersAPIDetail


# router = routers.SimpleRouter()
# router.register()

urlpatterns = [
    path('staff/', WorkersListView.as_view(), name='workers-list-url'),
    path('staff/<pk>/', WorkersDetailView.as_view(), name='workers-detail-url'),

    path('api/staff/v1/workers/', WorkersAPIList.as_view()),
    path('api/staff/v1/workers/<int:id>/', WorkersAPIDetail.as_view())

]

ozone_v4/main_app/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from os.path import basename


class BasePost(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name='Заголовок',
        null=False,
        blank=False
    )
    subtitle = models.CharField(max_length=255, verbose_name='Подзаголовок')

    image_logo = models.ImageField(
        upload_to='main/news',
        verbose_name='Фотография',
    )

    body = models.TextField(verbose_name='Содержание')

    published = models.DateField(
        verbose_name='Опубликовано для пользователя'
    )

    STATUS_CHOICES = (
        ('DF', 'Черновик'),
        ('PB', 'Опубликовано')
    )

    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default='PB',
        verbose_name='Статус новости'
    )

    time_creation = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Добавлено в БД'
    )

    last_edit = models.DateTimeField(
        auto_now=True,
        verbose_name='Последнее изменение'
    )

    class Meta:
        abstract = True
        ordering = ['-published']


class News(BasePost):

    TAGS = (
        ("WE", _("О нас")),
        ("SCI", _("Наука")),
    )

    tag = models.CharField(
        max_length=3,
        choices=TAGS,
        default='WE',
        verbose_name='Тэг'
    )

    def __str__(self):
        return f'News | {self.title} | {self.published}'

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['-published']


class Article(BasePost):

    body = models.TextField(
        verbose_name='Содержание',
        null=True,
        blank=True
    )

    def __str__(self):
        return f'Article | {self.title} | {self.published}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['-time_creation']


class ArticleFile(models.Model):
    """Файлы, прикрепляемые к статьям (Article)"""

    article = models.ForeignKey(
        to=Article,
        on_delete=models.CASCADE,
        related_name="article_files"
    )

    file = models.FileField(
        upload_to="main/base_post_attach",
        verbose_name="Файл"
    )

    def filename(self):
        return basename(self.file.name)

    def __str__(self):
        return f'{self.article} | {self.pk}'

    class Meta:
        verbose_name = 'Файл к Статье'
        verbose_name_plural = 'Файлы к Статьям'
        ordering = ['article']


class AnnualReport(models.Model):
    year = models.IntegerField(verbose_name='Год')
    report_file = models.FileField(
        upload_to='observations/reports',
        verbose_name='Файл отчёта'
    )

    last_edit = models.DateTimeField(
        auto_now=True,
        verbose_name='Последнее изменение'
    )

    def __str__(self):
        return f'Отчёт за {self.year} год'

    class Meta:
        verbose_name = 'Годовой отчёт'
        verbose_name_plural = 'Годовые отчёты'
        ordering = ['-year']


class Document(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название')

    description = models.TextField(
        max_length=455,
        null=True,
        blank=True,
        verbose_name='Описание'
    )

    document = models.FileField(
        upload_to='main/documents',
        verbose_name='Файл документа'
    )

    time_creation = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Добавлено в БД'
    )

    last_edit = models.DateTimeField(
        auto_now=True,
        verbose_name='Последнее изменение'
    )

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Документация'
        verbose_name_plural = 'Документация'
        ordering = ['-time_creation']


class Devices(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    subtitle = models.CharField(max_length=200, verbose_name='Предназначение')

    description = models.TextField(max_length=1500, verbose_name='Описание')

    main_image = models.ImageField(
        upload_to='main/devices',
        verbose_name='Главная фотография'
    )

    time_creation = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Добавлен в БД'
    )

    last_edit = models.DateTimeField(
        auto_now=True,
        verbose_name='Последнее изменение'
    )

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Прибор'
        verbose_name_plural = 'Приборы'
        ordering = ['-time_creation']


class DevicesCharacteristic(models.Model):
    ''' Технические характеристики прибора'''

    device = models.ForeignKey(
        Devices,
        on_delete=models.CASCADE,
        verbose_name='Прибор',
        related_name='characteristics'
    )

    characteristic_name = models.CharField(
        max_length=70,
        verbose_name='Характеристика'
    )

    characteristic_value = models.CharField(
        max_length=20,
        verbose_name='Значение'
    )

    time_creation = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Добавлен в БД'
    )

    last_edit = models.DateTimeField(
        auto_now=True,
        verbose_name='Последнее изменение'
    )

    def __str__(self):
        return f'{self.device}|{self.characteristic_name}'

    class Meta:
        verbose_name = 'Характеристика прибора'
        verbose_name_plural = 'Характеристики прибора'
        ordering = ['device', '-time_creation']

ozone_v4/templates/article-single.html
{% extends 'base.html' %}
{% load i18n static %}

{% block content %}
  <main id="main">

    <!-- ======= Blog Single Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="450">

        <div class="row justify-content-center">

          <div class="col-lg-9 entries ">

            <article class="entry entry-single">

                <div class="entry-img">
                  <img src="{{ object.image_logo.url }}" alt="" class="img-fluid">
                </div>

                <h2 class="entry-title">
                {{ object.title }}
                </h2>

                <p class="entry-subtitle">
                {{ object.subtitle }}
                </p>

                <div class="entry-content">
                    <p>{{ object.body|linebreaks }}</p>
                </div>

                {% if object.article_files.all %}
                    <div class="entry-attach">

                        <h6 class="entry-attach__head">{% trans 'К прочтению' %}</h6>

                        <div class="entry-attach__files">
                            {% for article_file in object.article_files.all %}
                                <a href="{{ article_file.file.url }}">{{article_file.filename}}</a>
                                &nbsp
                            {% endfor %}
                        </div>

                    </div>
                {% endif %}

                <div class="entry-meta">
                    <i class="bi bi-clock"></i>
                    <time datetime="2020-01-01">{{ object.published }}</time>
                </div>

            </article>
          </div>
        </div>
      </div>
    </section>

  </main>

  <script>
    const pageTitle = document.querySelector('title')
    pageTitle.innerHTML = 'Научные труды'

    const activeNavPage = document.querySelectorAll('.navbar-list>li>a')[1]
    activeNavPage.classList.add('active')
  </script>

{% endblock %}

ozone_v4/templates/articles.html
{% extends 'base.html' %}
{% load i18n static %}

{% block content %}

    <main id="main">

        <section id="blog" class="news blog">
            <div class="container">
                <div class="section-title">
                    <h2>{% trans 'Научные труды' %}</h2>
                </div>

                <blockquote class="annual-blockquote col-lg-12 col-sm-12 mb-5" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="650">
                    <p class="annual-text">
                        {% trans 'Мониторинг озонового слоя представляет собой систему наблюдений за состоянием озонового слоя, а также оценку и прогнозирование его изменений в целях своевременного выявления негативных воздействий природных и антропогенных факторов. Ежегодные отчеты по мониторингу озонового слоя:' %}

                        &nbsp

                        {% for report in annual_reports %}
                            <a href="url 'report.report_file.url' ">{{report.year}}</a>
                            &nbsp
                        {% endfor %}
                    </p>
                </blockquote>


                <div class="row d-flex flex-wrap">

                    {% for article_item in page_obj %}
                        <div class="col-lg-6 col-sm-12 mb-5"  data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="650">
                            <div class="card align-items-stretch">
                                <div class="card-img card-img_blog">
                                    <img src="{{ article_item.image_logo.url }}" class="" alt="...">
                                </div>
                                <div class="card-body card-body_blog">
                                    <h5 class="card-title"><a href="{{ article_item.id }}">{{ article_item.title }}</a></h5>
                                    <p class="card-text text-center">{{ article_item.subtitle }}</p>
                                    <div class="card-meta d-flex justify-content-between align-items-center">
                                        <div class="date">
                                            <i class="bi bi-clock"></i>
                                            <time>{{ article_item.published }}</time>
                                        </div>
                                        <div class="read-more">
                                            <a href="{{ article_item.id }}">{% trans 'Подробнее' %}</a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="blog-pagination">
                    
                    <ul class="justify-content-center">
                        {% for p in page_obj.paginator.page_range %}
                            {% if page_obj.number == p %}

                            <li class="active"><a href="?page={{p}}">{{p}}</a></li>

                            {% else %}
                            <li><a href="?page={{p}}">{{p}}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </section>
    </main>

    <script>

        const pageTitle = document.querySelector('title')
        pageTitle.innerHTML = 'Статьи'

        const activeNavPage = document.querySelectorAll('.navbar-list>li>a')[1]
        activeNavPage.classList.add('active')

    </script>

{% endblock %}

ozone_v4/templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load i18n static %}

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% trans 'ННИЦ МО БГУ' %}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/favicon-32x32.png' %}" rel="icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/extension.css' %}" rel="stylesheet">

    <!-- Vue CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.7.8/vue.min.js"></script>

    <!-- Axios CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.6.0/axios.min.js"></script>


    <!-- =======================================================
    * Template Name: Moderna
    * Updated: Sep 18 2023 with Bootstrap v5.3.2
    * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>
    <div class="wrapper">
        <header id="header" class="fixed-top d-flex align-items-center">

            <div class="container d-flex justify-content-between align-items-center">
                <div class="logo">
                    <a href="{% url 'main-page-url' %}">
                        <img src="{% static 'img/nomrec_logo3.png' %}" alt="" class="img-fluid">
                    </a>
                </div>

                <nav id="navbar" class="navbar">
                    <ul class="navbar-list">
                        <li><a href="{% url 'main-page-url' %}">{% trans 'Главная' %}</a></li>
                        <li class="dropdown"><a href="{% url 'about-page-url' %}">
                                <span>{% trans 'О нас' %}</span>
                                <i class="bi bi-chevron-down"></i></a>
                            <ul>
                                <li><a href="{% url 'about-page-url' %}">{% trans 'Общая информация' %}</a></li>
                                <li><a href="{% url 'workers-list-url' %}">{% trans 'Структура ННИЦ МО БГУ' %}</a></li>
                                <li><a href="{% url 'devices-page-url' %}">{% trans 'Приборная база' %}</a></li>
                                <li><a href="{% url 'articles-page-url' %}">{% trans 'Научно-исследовательская деятельность' %}</a></li>
                                <li><a href="https://tradeunion.bsu.by/">{% trans 'Профсоюз работников БГУ' %}</a></li>
                                <li><a href="{% url 'cookies-page-url' %}">{% trans 'Политика конфиденциальности' %}</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'blog-page-url' %}">{% trans 'Новости' %}</a></li>

                        <li class="dropdown"><a href="{% url 'observ-info-url' %}">
                                <span>{% trans 'Наблюдения' %}</span>
                                <i class="bi bi-chevron-down"></i></a>
                            <ul>
                                <li><a href="{% url 'observ-info-url' %}">{% trans 'Общая информация' %}</a></li>
                                <li><a href="{% url 'observ-download-url' %}">{% trans 'Архив наблюдений' %}</a></li>
                            </ul>
                        </li>

                        <li><a href="{% url 'documents-page-url' %}">{% trans 'Документация' %}</a></li>

                    </ul>
                    <i class="bi bi-list mobile-nav-toggle"></i>
                </nav><!-- .navbar -->

                <div class="d-flex align-items-center">
                    <div class="search">
                        <form action="{% url 'search-page-url' %}" method="get">
                            <input name="search" type="text" placeholder={% trans "Поиск . . ." %} autocomplete="off">
                        </form>
                    </div>
                    <button class="bad-vision" onclick="badVision">
                        <i class="bi bi-eyeglasses h2"></i>
                    </button>
                    <form action="{% url 'set_language' %}" method="post" class="language-switcher">
                      {% csrf_token %}
                      <input name="next" type="hidden" value="{{ redirect_to }}">
                      <select name="language" onchange="this.form.submit()">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                          <option class="language-option" value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                            {{ language.code }}
                          </option>
                        {% endfor %}
                      </select>
                    </form>
                </div>
            </div>
        </header>
        {% block content %}
        {% endblock %}
        <!-- ======= Footer ======= -->
        <div class="cookies">
            <header class="cookies__header">
                <i class="bi bi-cookie h4"></i>
                <h3>Cookies</h3>
            </header>
            <p class="cookies__info">
                {% trans 'Сайт использует только cookie, необходимые для корректной и безопасной работы сайта. Cookies не хранят никакой информации о пользователях и его действиях на сайте. Потробнее о политике cookie можно прочитать' %}
                <a href="{% url 'cookies-page-url' %}" class="cookies__url">{% trans "здесь" %}</a>.
            </p>
            <div class="cookies__buttons">
                <button id="acceptBtn" class="cookies__button cookies__button_accept">
                    {% trans "Принять" %}
                </button>
                <a href="{% url 'cookies-page-url' %}" id="detailBtn" class="cookies__button cookies__button_details">
                    {% trans "Подробнее" %}
                </a>
            </div>
        </div>

        <footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="700">
            <div class="footer-top">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 col-md-6 footer-contact">
                            <h4>{% trans 'ННИЦ МО' %}</h4>
                            <ul class="footer-list">
                                <li>{% trans 'г. Минск, ул. Курчатова 7, к. 907' %}</li>
                                <li>{% trans '220064, Республика Беларусь' %}</li>
                                <li> <strong>{% trans 'Телефон' %}:</strong> <a href="tel:+375173993611">+375 (17) 399-36-11</a></li>
                                <li><strong>{% trans 'Телефон' %}:</strong> <a href="tel:+375173185312">+375 (17) 318-53-12</a></li>
                                <li><strong>Email:</strong> <a href="mailto:nomrec@bsu.by">nomrec@bsu.by</a></li>

                            </ul>
                            <div class="social-links mt-3">
                                <a href="https://web.telegram.org/k/#@nomrec" class="twitter"><i
                                        class="bx bxl-telegram"></i></a>
                                <a href="https://m.facebook.com/groups/300381939614203/?ref=share&mibextid=NSMWBT" class="facebook"><i class="bx bxl-facebook"></i></a>
                                <a href="https://www.instagram.com/nomrec/" class="instagram"><i class="bx bxl-instagram"></i></a>
                            </div>

                        </div>
                        <div class="col-lg-4 col-md-6 footer-contact">
                            <h4>{% trans 'БГУ' %}</h4>
                            <ul class="footer-list">
                                <li>{% trans 'г. Минск, пр. Независимости, 4' %}</li>
                                <li>{% trans '220030, Республика Беларусь' %}</li>
                                <li><strong>{% trans 'Сайт' %}: </strong><a href="https://bsu.by">bsu.by</a></li>
                                <li> <strong>{% trans 'Телефон' %}:</strong><a href="tel:+375172095044">+ 375 17 209-50-44 {% trans '(справочная)' %}</a></li>
                                <li><strong>{% trans 'Моб. телефон:' %}</strong><a href="tel:+375172705940">+ 375 17 270-59-40 {% trans '(факс)' %}</a></li>
                                <li><strong>Email:</strong> <a href="mailto:bsu@bsu.by">bsu@bsu.by</a></li>

                            </ul>
                        </div>
                        <div class="col-lg-4 col-md-6 footer-contact">
                            <h4>{% trans 'Ссылки' %}</h4>

                            <div class="footer-link">
                                <a href="{% url 'cookies-page-url' %}" target="_blank">
                                    {% trans 'Политика cookies' %}
                                </a>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    Copyright &copy; 2024 <strong><span>NOMREC BSU</span></strong>. All Rights Reserved
                </div>
                <div class="credits">
                    <!-- All the links in the footer should remain intact. -->
                    <!-- You can delete the links only if you purchased the pro version. -->
                    <!-- Licensing information: https://bootstrapmade.com/license/ -->
                    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/ -->
                    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
            </div>
        </footer>
        <!-- Vendor JS Files -->
        <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
        <script src="{% static 'vendor/aos/aos.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
        <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
        <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>

        <!-- Template Main JS File -->
        <script src="{% static 'js/main.js' %}"></script>
    </div>

</body>

</html>

ozone_v4/templates/blog-single.html
{% extends 'base.html' %}
{% load i18n static %}

{% block content %}
  <main id="main">

    <!-- ======= Blog Single Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="450">

        <div class="row justify-content-center">

          <div class="col-lg-9 entries ">

            <article class="entry entry-single">

                <div class="entry-img">
                  <img src="{{ object.image_logo.url }}" alt="" class="img-fluid">
                </div>

                <h2 class="entry-title">
                {{ object.title }}
                </h2>

                <p class="entry-subtitle">
                {{ object.subtitle }}
                </p>

                <div class="entry-content">
                    <p>{{ object.body|linebreaks }}</p>
                </div>

                <div class="d-flex justify-content-between align-items-center">
                    <div class="entry-meta">
                        <i class="bi bi-clock"></i>
                        <time>{{ object.published }}</time>
                    </div>

                    <div class="news-tag">
                        <p class="mb-0">#{% trans object.get_tag_display %}</p>
                    </div>
                </div>

            </article>
          </div>
        </div>
      </div>
    </section>

  </main>

  <script src="{% static 'js/blog/editDOM.js' %}"></script>

{% endblock %}

ozone_v4/templates/cookies.html
{% extends 'base.html' %}
{% load i18n static %}


{% block content %}
    <!-- ======= Main Section ======= -->
<main id="main">
    <section class="about">
        <div class="container">

            <div class="section-title">
                <h2>{% trans 'Политика использования файлов cookie' %}</h2>
            </div>

            <div class="history__body">
                <div class="history__abstracts">
                    <blockquote class="annual-blockquote">
                        <p class="history__abstract">
                            Cookie представляют собой небольшие файлы, которые сохраняются в вашем интернет-браузере
                            или в операционной системе вашего компьютера (мобильного устройства) при использовании Сайта.
                            Часто cookie содержат информацию о предыдущих посещениях вами сайта. Cookie позволяютсохранить ранее введённые на сайте данные,
                            благодаря чему их не требуется вводить заново при следующем посещении сайта или при переходе между страницами сайта.
                        </p>

                        <p class="history__abstract">
                            Утверждение Положения о политике в отношении обработки персональных данных и cookie
                            является одной из принимаемых ННИЦ МО БГУ мер по защите персональных данных
                            предусмотренных Законом Республики Беларусь от 7 мая 2021 г. № 99-З «О защите персональных данных».
                        </p>

                        <p class="history__abstract">
                            Сайт nomrec.bsu.by использует файлы cookie, необходимые для надлежащего функционировани веб-сайта www.nomrec.bsu.by.
                            <u> Сайт не хранит информации о действиях и сессиях, произведённых пользователями сайта.
                                Согласано Общему регламенту о защите данных (GDPR), файлы cookie, использующиеся на сайте относятся к категории "Строго обязательные"
                                и  не могут быть отменены.</u>
                        </p>
                        <h5>Список используемых куки-файлов:</h5>
                        <ul>
                            <li class="history__abstract">csrf_token - обеспечивает защиту сайта CSRF-атак (Cross-site request forgery)</li>
                            <li class="history__abstract">django_language - на <u>период сессии пользователя (до момента закрытия браузера)</u> хранит информацию о выбранном языке сайта</li>
                            <li class="history__abstract">session_id - используется <u>только для администратора сайта</u> в качестве иденцификации. Хранится только в его браузере</li>
                            <li class="history__abstract">cookies_functional - менеджер управления вышеописанными файлами cookie</li>
                        </ul>

                     </blockquote>
                </div>
            </div>

        </div>
    </section>


</main>

    <script src="{% static 'js/about/editDOM.js' %}"></script>

{% endblock %}

ozone_v4/templates/devices-single.html
{% extends 'base.html' %}
{% load i18n static %}


{% block content %}
<main id="main">

    <section class="documetns">
        <div class="container">

            <div class="section-title">
                <h2> {{ object.name }} </h2>
            </div>

            <div class="row justify-content-center" data-aos="fade-up" data-aos-easing="ease-in-out"
                data-aos-duration="650">
                <div class="col-lg-3">
                    <div class="device__img">
                        <img src=" {{object.main_image.url }} " alt="">
                    </div>
                </div>
                <div class="col-lg-7 pt-4 pt-lg-0">
                    <h3>{{ object.subtitle }}</h3>
                    <p>{{ object.description }}</p>
                </div>
            </div>

        </div>
    </section>

    <section data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="750" class="pt-0">
        <div class="list-block ">
            <div class="container">
                <div class="section-title">
                    <h2>{% trans 'Технические характеристики' %} </h2>
                </div>

                <div class="list-block__list">
                    {% for char in object.characteristics.all %}

                    <div class="list-block__item">
                        <span class="list-block__item-desciption col-lg-7 col-md-9">
                            <i class="col-1 bi bi-gear"></i>&nbsp&nbsp{{ char.characteristic_name }}
                        </span>
                        <span class="list-block__item-desciption col-lg-2 col-md-2">
                            {{ char.characteristic_value }}
                        </span>

                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

</main>



<script>

    const pageTitle = document.querySelector('title')
    pageTitle.innerHTML = 'Приборы'

    const activeNavPage = document.querySelectorAll('.navbar-list>li>a')[1]
    activeNavPage.classList.add('active')

</script>

{% endblock %}